service: notes-app-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

providor:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-southeast-2

# 'iamRoleStatement' defines the permission policy for the Lambda function.
# In this case Lambda funtions are granted with permissions to access DynamoDB
iamRoleStatements:
  - Effect: allow
    Action: 
      - dynamodb: DescripeTable
      - dynamodb: Query
      - dynamodb: Scan
      - dynamodb: GetItem
      - dynamodb: PutItem
      - dynamodb: UpdateItem
      - dynamodb: DeleteItem
    Resource: "arn:aws:dynamodb:ap-southeast-2:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /notes
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain API call
  # - authorizer: authenticate using the AWS IAM role
  create:
    handler: create.main
    eventes:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam

